### ISSUE TITLE
Add 'Your online choices' companies

### ISSUE THREAD

**Issue by baltpeter** [datenanfragen/data#23]
Great list of advertising companies: http://www.youronlinechoices.com/uk/your-ad-choices

**Comment by baltpeter** [comment]
Also: v

**Comment by baltpeter** [comment]
Started work on this on the `b_adtech` branch. Still a lot to do, though…

**Comment by baltpeter** [comment]
All 'Your online choices' are now added. Now, I need to check if the other lists contain any new companies.

**Comment by zner0L** [comment]
What would actually be really nice would be to also add the identifiers cookie names into the database so that we could show people how to identify themselves to tracking companies. The "your online choices" website actually does quite a lot with your identifiers so taking a look at their website could actually tell us something about that.
