### ISSUE TITLE
German access request might be disrespectful

### ISSUE THREAD

**Issue by m-rey** [datenanfragen/data#314]
I've gotten a reply form an institution where I've requested access to my data.
They've informed me that the request might come as a bit disrespectful, because the text has:
* no formal greeting https://github.com/datenanfragen/data/blob/b7a3a27ffb2af3bbb5ec8c8c57e1997a649fc3da/templates/de/access-default.txt#L1
* a threat of legal action https://github.com/datenanfragen/data/blob/b7a3a27ffb2af3bbb5ec8c8c57e1997a649fc3da/templates/de/access-default.txt#L24

and thus have considered my request as inappropriate.
I think we should try to fix it. I've addressed the first point in PR #313

**Comment by zner0L** [comment]
Apart from the fact that controllers are still required to fully answer you request even if it is a little disrespectful, I beg to disagree.
The greeting show the appropriate amount of respect, while still being gender neutral. Something like "Sehr geehrte Damen und Herren" wouldn't be (Even if, like you did, we would add the asterisks. I would argue that most controllers would probably be rather confused. We want to avoid that ambiguity).
Informing the controller that you are willing to take legal action is often times the only way to actually get an answer. In my experience this has proven to be true. We believe that protection of your right to privacy is important, and we want the controller to take you seriously.  

Thank you still for point that out. I would recommend rephrasing the request if you are requesting someone close to you, like your sports club.

**Comment by baltpeter** [comment]
Thanks for the note. I have to agree with @zner0L that I am rather confused about that reply.

We specifically picked `Guten Tag` instead of `Sehr geehrte [was auch immer]` because it is gender-neutral without needing additional syntactic elements not commonly understood by people (`*` – or the `_` we usually use elsewhere).  
I would not classify that as disrespectful either. It seems completely appropriate to me as a formal greeting.

As for the note of potential legal consequences: I honestly see that as more of a courtesy than a threat. :D You are not required to inform the controller before taking legal option but it does indeed sometimes help to have the controller take you more seriously, as @zner0L pointed out. 

--

I am curious: Did they actually refuse your request or just note that in their reply? In the former case, I would definitely file a complaint with a supervisory authority. That would be unacceptable.

**Comment by m-rey** [comment]
Thank you for your responses.
The person who replied is the "Datenschutzbeauftragter" of an university. He stated that he's not responsible for such kind of requests, because he has a control role and therefore has no access to relevant files.
Thus he says that I should contact the organizational units of the university instead.
It is quite confusing to say the least.

**Comment by zner0L** [comment]
The person is definitely responsible. The least he could do is forward your request to the responsible organizational units. He might ask you what information you specifically want (according to recital 63) but you should be able to access all information. The controller should at least *try* to find your data, before they tell you that they can't. I would recommend asking a supervisory authority for support with your request.
